server:
  port: 8994
  context-path: /his
spring:
  application:
    name: his
  datasource:
      url: jdbc:mysql://rm-bp13w86vo1nrcb2l4.mysql.rds.aliyuncs.com/his?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
      username: acmed
      password: acmed8686
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

redis:
  ip: 106.14.145.251
  port: 6379
  password: medlion123456

mybatis:
  mapperLocations: classpath*:mapping/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback.xml

mapper:
    mappers:
        - com.acmed.his.util.TkMapper
    not-empty: false
    identity: MYSQL

weixin:
  appid: wx3d71d42f9956d861
  secret: 0cfc86874245070901f8b7059376fb1c
  mchId: 1492994072
  key: 3ef5f2a417ce47d0a8deaa6ef903f8f6
  certPath: apiclient_cert.p12
  url: http://wxpaytest.lanshiyihui.com:8994${server.context-path}

qiniu:
    bucket: jlhistest #七牛仓库
    accessKey: h6xfCteR-MvdFwf0Y44M6q6alGKBvnD2LQwNnUg_
    secretKey: fbSuf2EDMVETHUlx7Oo6YK5C8UeymNXJEmtN8Uh0
    imgurl: http://qntest.lanshiyihui.com

pagehelper:
    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
insurance:
    price: 200 #每个挂号收取 200分  既 2元