server:
  port: 9994
  context-path: /his
spring:
  application:
    name: his
  datasource:
      url: jdbc:mysql://115.29.47.72:3306/his?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
      username: acmed
      password: acmed8686
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

redis:
  ip: 115.29.47.72
  port: 6877
  password: acmedhis123456

mybatis:
  mapperLocations: classpath*:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback.xml

mapper:
    mappers:
        - com.acmed.his.util.TkMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

weixin:
  appid: wx7e396b520f901b15
  secret: a9bdaf563dd6a2cfd988153058021955
  mchId: 1301239801
  key: 3ef5f2a417ce47d0a8deaa6ef903f8f6
  certPath: apiclient_cert_jizhi.p12
  url: http://wxpaytest.lanshiyihui.com:8994${server.context-path}
qiniu:
    bucket: jlhistest #七牛仓库
    accessKey: h6xfCteR-MvdFwf0Y44M6q6alGKBvnD2LQwNnUg_
    secretKey: fbSuf2EDMVETHUlx7Oo6YK5C8UeymNXJEmtN8Uh0
    imgurl: http://qntest.lanshiyihui.com
zhangyao:
  url: http://presapi.lkhealth.net/index.php
insurance:
    price: 200 #每个挂号收取 200分  既 2元
